version: "3.2"

services:

  redis:
    image: redis:${REDIS_VERSION:-6.0-alpine}

  redis_data:
    build:
      context: .
    depends_on:
      - redis
    volumes:
      - "./data/dump.resp:/tmp/dump.resp"
