version: "3.2"

services:

  redis:
    image: redis:${REDIS_VERSION:-6.0-alpine}

  redis_data:
    build:
      context: ./docker/redis
    depends_on:
      - redis
    volumes:
      - "./docker/redis/data/dump.resp:/tmp/dump.resp"
