version: "3.8"

secrets:
  app_secrets:
    file: .secrets

services:
  app:
    build:
      context: .
      args:
        DOCKER_BUILDKIT: 1
      secrets:
        - app_secrets
    image: app_name
    command: ruby -e "puts 'app is OK'"
